### ISSUE TITLE
Update for scilab 6

### ISSUE THREAD

**Issue by doquen** [siddhu8990/Scilab2C#17]
Hi:
Will this be updated for scilab 6? How is this project related to this one: 
https://github.com/scilab/scilab2c

**Comment by siddhu8990** [comment]
Hi,

Thanks for your interest. 
This is same as [https://github.com/scilab/scilab2c](https://github.com/scilab/scilab2c). This was my own repo earlier which was later moved to new location. Please follow  [https://github.com/scilab/scilab2c](https://github.com/scilab/scilab2c) as it is updated regularly now and not this one.

**Comment by doquen** [comment]
Hi:
Thanks! i've also written an issue with some errors in https://github.com/scilab/scilab2c but i got no response... i guess i'll wait till i get answer from then.
Thanks!
